/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as ApiPublicNotifyNewTicketRouteImport } from './routes/api/public/notify-new-ticket'
import { Route as CSlugIndexRouteImport } from './routes/c/$slug/index'
import { Route as CSlugLoginRouteImport } from './routes/c/$slug/login'
import { Route as CSlugTrackRouteImport } from './routes/c/$slug/track'
import { Route as AuthenticatedCSlugAdminRouteImport } from './routes/_authenticated/c/$slug/admin'
import { Route as AuthenticatedCSlugMeRouteImport } from './routes/_authenticated/c/$slug/me'
import { Route as ApiPublicAdminMemberDeleteRouteImport } from './routes/api/public/admin-member/delete'
import { Route as ApiPublicAdminPasswordSetRouteImport } from './routes/api/public/admin-password/set'
import { Route as ApiPublicAuthOtpSendRouteImport } from './routes/api/public/auth-otp/send'
import { Route as ApiPublicAuthOtpVerifyRouteImport } from './routes/api/public/auth-otp/verify'
import { Route as ApiPublicAuthResetSendRouteImport } from './routes/api/public/auth-reset/send'
import { Route as ApiPublicSubscriptionExpiryNotifyRouteImport } from './routes/api/public/subscription-expiry/notify'
import { Route as AuthenticatedCSlugTicketsTicketIdRouteImport } from './routes/_authenticated/c/$slug/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicNotifyNewTicketRoute =
  ApiPublicNotifyNewTicketRouteImport.update({
    id: '/api/public/notify-new-ticket',
    path: '/api/public/notify-new-ticket',
    getParentRoute: () => rootRouteImport,
  } as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/c/$slug/',
  path: '/c/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugLoginRoute = CSlugLoginRouteImport.update({
  id: '/c/$slug/login',
  path: '/c/$slug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugTrackRoute = CSlugTrackRouteImport.update({
  id: '/c/$slug/track',
  path: '/c/$slug/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCSlugAdminRoute = AuthenticatedCSlugAdminRouteImport.update({
  id: '/c/$slug/admin',
  path: '/c/$slug/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCSlugMeRoute = AuthenticatedCSlugMeRouteImport.update({
  id: '/c/$slug/me',
  path: '/c/$slug/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAdminMemberDeleteRoute =
  ApiPublicAdminMemberDeleteRouteImport.update({
    id: '/api/public/admin-member/delete',
    path: '/api/public/admin-member/delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminPasswordSetRoute =
  ApiPublicAdminPasswordSetRouteImport.update({
    id: '/api/public/admin-password/set',
    path: '/api/public/admin-password/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthOtpSendRoute = ApiPublicAuthOtpSendRouteImport.update({
  id: '/api/public/auth-otp/send',
  path: '/api/public/auth-otp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthOtpVerifyRoute = ApiPublicAuthOtpVerifyRouteImport.update({
  id: '/api/public/auth-otp/verify',
  path: '/api/public/auth-otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthResetSendRoute = ApiPublicAuthResetSendRouteImport.update({
  id: '/api/public/auth-reset/send',
  path: '/api/public/auth-reset/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscriptionExpiryNotifyRoute =
  ApiPublicSubscriptionExpiryNotifyRouteImport.update({
    id: '/api/public/subscription-expiry/notify',
    path: '/api/public/subscription-expiry/notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCSlugTicketsTicketIdRoute =
  AuthenticatedCSlugTicketsTicketIdRouteImport.update({
    id: '/c/$slug/tickets/$ticketId',
    path: '/c/$slug/tickets/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/public/notify-new-ticket': typeof ApiPublicNotifyNewTicketRoute
  '/c/$slug/login': typeof CSlugLoginRoute
  '/c/$slug/track': typeof CSlugTrackRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/admin': typeof AuthenticatedCSlugAdminRoute
  '/c/$slug/me': typeof AuthenticatedCSlugMeRoute
  '/api/public/admin-member/delete': typeof ApiPublicAdminMemberDeleteRoute
  '/api/public/admin-password/set': typeof ApiPublicAdminPasswordSetRoute
  '/api/public/auth-otp/send': typeof ApiPublicAuthOtpSendRoute
  '/api/public/auth-otp/verify': typeof ApiPublicAuthOtpVerifyRoute
  '/api/public/auth-reset/send': typeof ApiPublicAuthResetSendRoute
  '/api/public/subscription-expiry/notify': typeof ApiPublicSubscriptionExpiryNotifyRoute
  '/c/$slug/tickets/$ticketId': typeof AuthenticatedCSlugTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/public/notify-new-ticket': typeof ApiPublicNotifyNewTicketRoute
  '/c/$slug/login': typeof CSlugLoginRoute
  '/c/$slug/track': typeof CSlugTrackRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/c/$slug/admin': typeof AuthenticatedCSlugAdminRoute
  '/c/$slug/me': typeof AuthenticatedCSlugMeRoute
  '/api/public/admin-member/delete': typeof ApiPublicAdminMemberDeleteRoute
  '/api/public/admin-password/set': typeof ApiPublicAdminPasswordSetRoute
  '/api/public/auth-otp/send': typeof ApiPublicAuthOtpSendRoute
  '/api/public/auth-otp/verify': typeof ApiPublicAuthOtpVerifyRoute
  '/api/public/auth-reset/send': typeof ApiPublicAuthResetSendRoute
  '/api/public/subscription-expiry/notify': typeof ApiPublicSubscriptionExpiryNotifyRoute
  '/c/$slug/tickets/$ticketId': typeof AuthenticatedCSlugTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/api/public/notify-new-ticket': typeof ApiPublicNotifyNewTicketRoute
  '/c/$slug/login': typeof CSlugLoginRoute
  '/c/$slug/track': typeof CSlugTrackRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/_authenticated/c/$slug/admin': typeof AuthenticatedCSlugAdminRoute
  '/_authenticated/c/$slug/me': typeof AuthenticatedCSlugMeRoute
  '/api/public/admin-member/delete': typeof ApiPublicAdminMemberDeleteRoute
  '/api/public/admin-password/set': typeof ApiPublicAdminPasswordSetRoute
  '/api/public/auth-otp/send': typeof ApiPublicAuthOtpSendRoute
  '/api/public/auth-otp/verify': typeof ApiPublicAuthOtpVerifyRoute
  '/api/public/auth-reset/send': typeof ApiPublicAuthResetSendRoute
  '/api/public/subscription-expiry/notify': typeof ApiPublicSubscriptionExpiryNotifyRoute
  '/_authenticated/c/$slug/tickets/$ticketId': typeof AuthenticatedCSlugTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/portal'
    | '/support'
    | '/api/public/notify-new-ticket'
    | '/c/$slug/login'
    | '/c/$slug/track'
    | '/c/$slug/'
    | '/c/$slug/admin'
    | '/c/$slug/me'
    | '/api/public/admin-member/delete'
    | '/api/public/admin-password/set'
    | '/api/public/auth-otp/send'
    | '/api/public/auth-otp/verify'
    | '/api/public/auth-reset/send'
    | '/api/public/subscription-expiry/notify'
    | '/c/$slug/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/portal'
    | '/support'
    | '/api/public/notify-new-ticket'
    | '/c/$slug/login'
    | '/c/$slug/track'
    | '/c/$slug'
    | '/c/$slug/admin'
    | '/c/$slug/me'
    | '/api/public/admin-member/delete'
    | '/api/public/admin-password/set'
    | '/api/public/auth-otp/send'
    | '/api/public/auth-otp/verify'
    | '/api/public/auth-reset/send'
    | '/api/public/subscription-expiry/notify'
    | '/c/$slug/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/support'
    | '/api/public/notify-new-ticket'
    | '/c/$slug/login'
    | '/c/$slug/track'
    | '/c/$slug/'
    | '/_authenticated/c/$slug/admin'
    | '/_authenticated/c/$slug/me'
    | '/api/public/admin-member/delete'
    | '/api/public/admin-password/set'
    | '/api/public/auth-otp/send'
    | '/api/public/auth-otp/verify'
    | '/api/public/auth-reset/send'
    | '/api/public/subscription-expiry/notify'
    | '/_authenticated/c/$slug/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicNotifyNewTicketRoute: typeof ApiPublicNotifyNewTicketRoute
  CSlugLoginRoute: typeof CSlugLoginRoute
  CSlugTrackRoute: typeof CSlugTrackRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
  ApiPublicAdminMemberDeleteRoute: typeof ApiPublicAdminMemberDeleteRoute
  ApiPublicAdminPasswordSetRoute: typeof ApiPublicAdminPasswordSetRoute
  ApiPublicAuthOtpSendRoute: typeof ApiPublicAuthOtpSendRoute
  ApiPublicAuthOtpVerifyRoute: typeof ApiPublicAuthOtpVerifyRoute
  ApiPublicAuthResetSendRoute: typeof ApiPublicAuthResetSendRoute
  ApiPublicSubscriptionExpiryNotifyRoute: typeof ApiPublicSubscriptionExpiryNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/notify-new-ticket': {
      id: '/api/public/notify-new-ticket'
      path: '/api/public/notify-new-ticket'
      fullPath: '/api/public/notify-new-ticket'
      preLoaderRoute: typeof ApiPublicNotifyNewTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/c/$slug'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/login': {
      id: '/c/$slug/login'
      path: '/c/$slug/login'
      fullPath: '/c/$slug/login'
      preLoaderRoute: typeof CSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/track': {
      id: '/c/$slug/track'
      path: '/c/$slug/track'
      fullPath: '/c/$slug/track'
      preLoaderRoute: typeof CSlugTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$slug/admin': {
      id: '/_authenticated/c/$slug/admin'
      path: '/c/$slug/admin'
      fullPath: '/c/$slug/admin'
      preLoaderRoute: typeof AuthenticatedCSlugAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$slug/me': {
      id: '/_authenticated/c/$slug/me'
      path: '/c/$slug/me'
      fullPath: '/c/$slug/me'
      preLoaderRoute: typeof AuthenticatedCSlugMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/admin-member/delete': {
      id: '/api/public/admin-member/delete'
      path: '/api/public/admin-member/delete'
      fullPath: '/api/public/admin-member/delete'
      preLoaderRoute: typeof ApiPublicAdminMemberDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-password/set': {
      id: '/api/public/admin-password/set'
      path: '/api/public/admin-password/set'
      fullPath: '/api/public/admin-password/set'
      preLoaderRoute: typeof ApiPublicAdminPasswordSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-otp/send': {
      id: '/api/public/auth-otp/send'
      path: '/api/public/auth-otp/send'
      fullPath: '/api/public/auth-otp/send'
      preLoaderRoute: typeof ApiPublicAuthOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-otp/verify': {
      id: '/api/public/auth-otp/verify'
      path: '/api/public/auth-otp/verify'
      fullPath: '/api/public/auth-otp/verify'
      preLoaderRoute: typeof ApiPublicAuthOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-reset/send': {
      id: '/api/public/auth-reset/send'
      path: '/api/public/auth-reset/send'
      fullPath: '/api/public/auth-reset/send'
      preLoaderRoute: typeof ApiPublicAuthResetSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscription-expiry/notify': {
      id: '/api/public/subscription-expiry/notify'
      path: '/api/public/subscription-expiry/notify'
      fullPath: '/api/public/subscription-expiry/notify'
      preLoaderRoute: typeof ApiPublicSubscriptionExpiryNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$slug/tickets/$ticketId': {
      id: '/_authenticated/c/$slug/tickets/$ticketId'
      path: '/c/$slug/tickets/$ticketId'
      fullPath: '/c/$slug/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedCSlugTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedCSlugAdminRoute: typeof AuthenticatedCSlugAdminRoute
  AuthenticatedCSlugMeRoute: typeof AuthenticatedCSlugMeRoute
  AuthenticatedCSlugTicketsTicketIdRoute: typeof AuthenticatedCSlugTicketsTicketIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedCSlugAdminRoute: AuthenticatedCSlugAdminRoute,
  AuthenticatedCSlugMeRoute: AuthenticatedCSlugMeRoute,
  AuthenticatedCSlugTicketsTicketIdRoute:
    AuthenticatedCSlugTicketsTicketIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicNotifyNewTicketRoute: ApiPublicNotifyNewTicketRoute,
  CSlugLoginRoute: CSlugLoginRoute,
  CSlugTrackRoute: CSlugTrackRoute,
  CSlugIndexRoute: CSlugIndexRoute,
  ApiPublicAdminMemberDeleteRoute: ApiPublicAdminMemberDeleteRoute,
  ApiPublicAdminPasswordSetRoute: ApiPublicAdminPasswordSetRoute,
  ApiPublicAuthOtpSendRoute: ApiPublicAuthOtpSendRoute,
  ApiPublicAuthOtpVerifyRoute: ApiPublicAuthOtpVerifyRoute,
  ApiPublicAuthResetSendRoute: ApiPublicAuthResetSendRoute,
  ApiPublicSubscriptionExpiryNotifyRoute:
    ApiPublicSubscriptionExpiryNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
